doname: fusarium_env2
channels:
  - anaconda
  - anaconda-fusion
  - defaults
  - conda-forge
  - esri
dependencies:
  - python==3.11
  - psycopg2
  - pandas
  - sqlalchemy
  - sqlalchemy-utils
  - pandas
  - partd
  - bokeh
  - schedule
  - pip
  - bs4
  - ipykernel
  - jupyter
  - pyodbc
  #- fakechroot
  - docker-py
  - python-dotenv
  - esri::arcgis
  #- pip:
  #  - git+https://github.com/blaze/dask.git#egg=dask[complete]