
services:
  python:
    build:
      context: ..
    environment:
      ENV_NAME: ${CONDA_ENV_NAME}
    volumes:
      - ./:/code
    #command: >
      # sh -c "python -u load_data.py --swarm"
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - ./ms_setup/init:/docker-entrypoint-initdb.d
      - ./mssql-data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PW}


volumes:
    mssql-dat





